// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5uIs6MJ8x0f2kL2YBpcmpB54jG0AWJhg',
    appId: '1:343767235488:web:134164c5703906c5e182c5',
    messagingSenderId: '343767235488',
    projectId: 'findapet-app-56a90',
    authDomain: 'findapet-app-56a90.firebaseapp.com',
    storageBucket: 'findapet-app-56a90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7IPLIhn0WGMlxfx65er4beUkrlF_eeM',
    appId: '1:343767235488:android:2258fbba2d74654ee182c5',
    messagingSenderId: '343767235488',
    projectId: 'findapet-app-56a90',
    storageBucket: 'findapet-app-56a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDZKhXcFx8Xm0k2GhUK3ipTcVZ3n4ntY',
    appId: '1:343767235488:ios:6c2c443b2b85369be182c5',
    messagingSenderId: '343767235488',
    projectId: 'findapet-app-56a90',
    storageBucket: 'findapet-app-56a90.appspot.com',
    iosBundleId: 'com.example.findapet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsDZKhXcFx8Xm0k2GhUK3ipTcVZ3n4ntY',
    appId: '1:343767235488:ios:6c2c443b2b85369be182c5',
    messagingSenderId: '343767235488',
    projectId: 'findapet-app-56a90',
    storageBucket: 'findapet-app-56a90.appspot.com',
    iosBundleId: 'com.example.findapet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5uIs6MJ8x0f2kL2YBpcmpB54jG0AWJhg',
    appId: '1:343767235488:web:702a717555d5b4b3e182c5',
    messagingSenderId: '343767235488',
    projectId: 'findapet-app-56a90',
    authDomain: 'findapet-app-56a90.firebaseapp.com',
    storageBucket: 'findapet-app-56a90.appspot.com',
  );
}
